mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),

]


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

shopapp/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from .views import (
    ProductsListView,
    ProductCreateView,
    ProductDetailsView,
    ProductUpdateView,
    ProductDeleteView,
    RegisterView,
    MyLogoutView,
    AboutMeView,
    AboutMeUpdateView,
    Search,
    view_cart,
    add_to_cart,
    remove_from_cart,
    create_order,
    ProductSortHView,
    ProductSortLView,
)
from .views import shop_index
app_name = "shopapp"
urlpatterns = [
    path("", shop_index, name="index"),
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", LoginView.as_view(template_name="shopapp/login.html",
                                     redirect_authenticated_user=True,), name="login"),
    path("logout/", MyLogoutView.as_view(), name='logout'),
    path("about-me/", AboutMeView.as_view(), name='about-me'),
    path("about-me/<int:pk>/update/", AboutMeUpdateView.as_view(), name="profile-update"),
    path("products/", ProductsListView.as_view(), name="products-list"),

    path("productsh/", ProductSortHView.as_view(), name="product-sorth"),
    path("productsl/", ProductSortLView.as_view(), name="product-sortl"),

    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/update/<int:pk>/", ProductUpdateView.as_view(), name="product_update"),
    path("products/delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/create", ProductCreateView.as_view(), name="product-create"),
    path("search", Search.as_view(), name="search"),
    path('cart/', view_cart, name='view_cart'),
    path('cart/add/<int:pk>/', add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:pk>/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', create_order, name='create_order'),
]

shopapp/models.py
from django.contrib.auth.models import User
from django.db import models

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    views_count = models.DecimalField(default=0, max_digits=8, decimal_places=0)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_name = models.CharField(max_length=100, null=False, blank=True)
    first_name = models.CharField(max_length=100, null=False, blank=True)
    email = models.CharField(max_length=100, null=False, blank=True)

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user}'s cart"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    class Meta:
        unique_together = ('cart', 'product')

    def __str__(self):
        return f"{self.quantity} x {self.product}"

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f"{self.user}'s order #{self.id}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    class Meta:
        unique_together = ('order', 'product')

    def __str__(self):
        return f"{self.quantity} x {self.product}"

shopapp/views.py
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpRequest

from django.contrib.auth import authenticate, login, logout
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.views.generic import TemplateView, CreateView, DeleteView, View
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from .models import Profile


from .models import Product, Cart, CartItem, Order, OrderItem
def shop_index(request: HttpRequest) -> HttpResponse:
    products = Product.objects.order_by('-id')[:3]
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    return render(request, 'shopapp/shop-index.html', context={'num_visits': num_visits, 'products': products})


class ProductsListView(ListView):
    template_name = "shopapp/products-list.html"
    context_object_name = "products"
    queryset = Product.objects.all()

class ProductSortHView(ListView):
    template_name = "shopapp/products-list.html"
    context_object_name = "products"
    queryset = Product.objects.all().order_by('-price')

class ProductSortLView(ListView):
    template_name = "shopapp/products-list.html"
    context_object_name = "products"
    queryset = Product.objects.all().order_by('price')


class ProductDetailsView(DetailView):
    template_name = 'shopapp/products-details.html'
    model = Product
    context_object_name = "product"

    def get_object(self):
        obj = super().get_object()
        obj.views_count += 1
        obj.save()
        return obj

class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "shopapp.add_product"

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products-list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        response = super().form_valid(form)
        return response

class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "shopapp.change_product"

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk}
        )



class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "shopapp.delete_product"

    model = Product
    template_name = 'shopapp/products-delete.html'

    def get_success_url(self):
        return reverse(
            "shopapp:products-list",
        )



class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")

        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "shopapp/register.html"
    success_url = reverse_lazy("shopapp:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")

        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class AboutMeView(TemplateView):
    template_name = "shopapp/about-me.html"

class AboutMeUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_staff:
            return True
        return True
    model = Profile
    fields = "user", 'last_name', 'first_name', 'email',
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:about-me",
        )

class MyLogoutView(LogoutView):
    next_page = reverse_lazy("shopapp:login")


class Search(ListView):
    template_name = "shopapp/products-list.html"
    context_object_name = "products"
    paginate_by = 5

    def get_queryset(self):
        return Product.objects.filter(name__iregex=self.request.GET.get('q'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context

def view_cart(request):
    cart = Cart.objects.get(user=request.user)
    cart_items = cart.cartitem_set.all()
    total = 0
    for item in cart_items:
        total += item.product.price * item.quantity
    context = {
        'cart': cart,
        'cart_items': cart_items,
        'total': total
    }
    return render(request, 'shopapp/cart.html', context)

def add_to_cart(request, pk):
    cart, created = Cart.objects.get_or_create(user=request.user)
    product = Product.objects.get(pk=pk)
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    if not created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('shopapp:view_cart')


def remove_from_cart(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk, cart__user=request.user)
    cart_item.delete()
    return redirect('shopapp:view_cart')

def create_order(request):
    cart = Cart.objects.get(user=request.user)
    cart_items = cart.cartitem_set.all()
    order = Order(user=request.user, total=0)
    order.save()
    for item in cart_items:
        order_item = OrderItem(order=order, product=item.product, quantity=item.quantity)
        order_item.save()
        order.total += item.product.price * item.quantity
    order.save()
    cart_items.delete()
    return redirect('shopapp:view_cart')

shopapp/templates/shopapp/about-me.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Профиль
{% endblock %}

{% block body %}
  <h1 style="color: white; text-align: center; font-size: 40px;">Мой профиль</h1>
  {% if user.is_authenticated %}
    <h2 style="color: white; padding-left: 120px; font-size: 40px;" >Данные:</h2>

      <p style="padding-left: 125px; color: white; text-shadow: 2px 2px 2px black;">Логин: {{ user.username }}</p>
      <p style="padding-left: 125px; color: white; text-shadow: 2px 2px 2px black;">Имя: {{ user.profile.last_name }}</p>
      <p style="padding-left: 125px; color: white; text-shadow: 2px 2px 2px black;">Фамилия: {{ user.profile.first_name }}</p>
      <p style="padding-left: 125px; color: white; text-shadow: 2px 2px 2px black;">E-mail: {{ user.profile.email }}</p>

  {% else %}
    <h2>Нет доступа!</h2>
  {% endif %}

  <div class="logout"><a style="padding-left: 120px; text-decoration: underline; color: white; font-size: 20px;" href="{% url 'shopapp:profile-update' pk=user.profile.pk %}">Редактировать профиль</a></div>
  <div class="logout"><a style="padding-left: 120px; text-decoration: underline; color: white; font-size: 20px;" href="{% url 'shopapp:logout'%}">Выйти из профиля</a></div>

{% endblock %}

shopapp/templates/shopapp/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'shopapp/css/style.css' %}">
    <title>{% block title %}
      Base title
    {% endblock %}</title>
</head>
<header>
    {% block header %}
    <div class="header">
        <div class="logotype">TEAhouse</div>
        <div class="nav">
            <a class="home" href="{% url 'shopapp:index'%}">Главная</a>
            <a class="catalog" href="{% url 'shopapp:products-list'%}">Каталог </a>
            <a class="contacts" href="#cont">Контакты</a>
            {% if user.is_authenticated %}
                <a class="profile" href="{% url 'shopapp:about-me'%}">Профиль</a>
            {% else %}
                <a class="profile" href="{% url 'shopapp:login'%}">Войти в профиль</a>
                <a class="profile" href="{% url 'shopapp:register'%}">Зарегистрироваться</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a class="cart" href="{% url 'shopapp:view_cart'%}">Корзина</a>
            {% endif %}
        </div>
    </div>
    {% endblock %}
</header>
<body>

{% block body %}
  Base body
{% endblock %}

{% block footer %}
  <div id="cont" class="contacts_footer">
    <h1>Контакты:</h1>
    <p>Email: teahouse.com</p>
    <p>Телефон: 8-800-555-35-35</p>
    <p>Адресс: г.Владивосток ул.Державина 57</p>
  </div>
{% endblock %}
</body>
</html>

shopapp/templates/shopapp/cart.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Корзина
{% endblock %}

{% block body %}
    <h1 style="text-align: center; color: white; font-size: 40px;">Корзина</h1>
    {% if cart_items %}
    <div style="padding-left: 750px;">
        <table style="text-align: center;color: white; font-size: 20px;">
            <tr>
                <th>Товар</th>
                <th>Цена</th>
                <th>Количество</th>
                <th></th>
            </tr>
            {% for item in cart_items %}
                <tr>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.product.price }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <form action="{% url 'shopapp:remove_from_cart' item.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Удалить</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="3"><strong>Всего к оплате:</strong></td>
                <td>{{ total }}руб.</td>
                <td></td>
            </tr>
        </table>
        <form style="text-align: center; padding-bottom: 50px;" action="{% url 'shopapp:create_order'%}" method="post">
            {% csrf_token %}
            <button type="submit">Оформить заказ</button>
        </form>
    </div>
    {% else %}
        <h3 style="text-align: center;color: white; font-size: 20px;">Пусто </h3>
    {% endif %}
{% endblock %}

shopapp/templates/shopapp/login.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}
  <h1 style="padding-left: 120px; color: white; font-size: 40px;">Авторизация</h1>
  <form method="POST" style="padding-left: 120px; padding-bottom: 50px; padding-top: 50px;">
    {% csrf_token %}

     {{ form.non_field_errors }}

        <div class="form-group">
            <label for="{{ form.username.id_for_label }}">Логин:</label>
            {{ form.username }}
            {{ form.username.errors }}
        </div>

        <div class="form-group" style="padding-top: 50px; padding-bottom: 50px;">
            <label for="{{ form.password.id_for_label }}">Пароль:</label>
            {{ form.password }}
            {{ form.password.errors }}
        </div>

    <button type="submit">Войти</button>
  </form>
{% endblock %}

shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Добавить товар
{% endblock %}

{% block body %}
  <h1>Добавляем чай</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Добавить</button>
    </form>
  </div>
  <div>
    <a style="text-decoration: underline; color: white;" href="{% url 'shopapp:products-list' %}"
    >Назад </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update Product
{% endblock %}

{% block body %}
  <h1 style="padding-left: 120px; color: white; font-size: 40px;">Редактировать товар</h1>
  <div>
    <form method="POST" enctype="multipart/form-data"  style="padding-left: 120px; padding-bottom: 50px; padding-top: 50px;">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">Сохранить</button>
    </form>
  </div>

  <div>
        <a style="padding-left: 120px; text-decoration: underline; color: white; font-size: 20px;" href="{% url 'shopapp:product_details' pk=object.pk %}">Назад</a>
  </div>
{% endblock %}

shopapp/templates/shopapp/products-delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product {{ product.pk }}
{% endblock %}

{% block body %}
  <div>
    <h1 style="color: white; text-align: center;"><strong>Удаление товара {{ product.name }}</strong></h1>
    <div style="color: white; text-align: center;">
        <div>
            {% if product.preview %}
                <img style="width: 400px; height: 250px" src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
            {% endif %}
        </div>
        <h1 style="color: white; text-align: center; text-shadow: 1px 1px 2px black;"><strong>{{ product.name }}</strong></h1>
        <div style="text-shadow: 1px 1px 2px black;">
            Описание:
            <en>{{ product.description }}</en>
        </div>
    </div>
    <form method="post" style="padding-left: 120px; padding-bottom: 50px; padding-top: 50px;">
      {% csrf_token %}
      <button style="background-color: white; color: black;" type="submit">Удалить товар</button>
    </form>
  </div>
  <div>
    <a style="text-decoration: underline;padding-left: 120px; color: white;" href="{% url 'shopapp:products-list' %}"
    >Назад</a>
  </div>
{% endblock %}

shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product {{ product.pk }}
{% endblock %}

{% block body %}
    <h1 style="color: white; text-align: center;"><strong>{{ product.name }}</strong></h1>
    <div style="color: white; text-align: center;">
        <div>
            {% if product.preview %}
                <img style="width: 400px; height: 250px" src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
            {% endif %}
        </div>
        <div style="text-shadow: 1px 1px 2px black;">
            Описание:
            <en>{{ product.description }}</en>
        </div>
        <div style="text-shadow: 1px 1px 2px black;">
            Цена:
            <en>{{ product.price }} руб.</en>
        </div>
        <div style="text-shadow: 1px 1px 2px black;">
            Скидка:
            <en>{{ product.discount }} руб.</en>
        </div>
        <div style="text-shadow: 1px 1px 2px black;">
            Кол-во просмотров:
            <en>{{ product.views_count }} раз(-a)</en>
        </div>
    </div>

    <div>
        <a style="padding-left: 150px; text-decoration: underline; color: white; font-size: 20px;" href="{% url 'shopapp:add_to_cart' product.pk %}">Добавить в корзину</a>
        <br>
    </div>
    {% if perms.shopapp.change_product %}
        <div>
            <a style="padding-left: 150px; text-decoration: underline; color: white; font-size: 20px;" href="{% url 'shopapp:product_update' pk=product.pk %}">Редактировать</a>
            <br>
        </div>
    {% endif %}

    {% if perms.shopapp.delete_product %}
        <div>
            <a style="padding-left: 150px; text-decoration: underline; color: white; font-size: 20px;" href="{% url 'shopapp:product_delete' pk=product.pk %}">Удалить</a>
            <br>
        </div>
    {% endif %}


    <div>
        <a style="padding-left: 150px; text-decoration: underline; color: white; font-size: 20px;" href="{% url 'shopapp:products-list' %}">Назад </a>
    </div>

{% endblock %}

shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    чай
{% endblock %}

{% block body %}
    <div style="text-align: right; padding-right: 120px; padding-top: 20px;">
        <form action="{% url 'shopapp:search' %}" method="GET">
            <input type="search" type="text" name="q" placeholder="Поиск">
            <button style="text-shadow: 1px 1px 2px black; color: white; background-color: black;" type="submit">Поиск</button>
            <br>
            <button style="margin-top: 5px; width: 234px; text-shadow: 1px 1px 2px black; color: white; background-color: black;" type="submit">Сбросить параметры поиска</button>
        </form>
    </div>

    <p><a href="{% url 'shopapp:product-sorth' %}">От высокой </a></p>
    <p><a href="{% url 'shopapp:product-sortl' %}">От низкой </a></p>



    <h1 style="text-align: center; color: white; font-size: 40px;">Каталог </h1>
     {% if products %}
        <div  style="display: flex; justify-content: center;">
            {% for product in products %}
                <div style="color: white; text-align: center;">
                    <h1><a style="text-decoration: underline; color: white;" href="{% url 'shopapp:product_details' pk=product.pk %}">{{ product.name }}</a></h1>
                    <div>
                        {% if product.preview %}
                          <img style="width: 400px; height: 250px" src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                        {% endif %}
                    </div>
                    <p style="text-shadow: 1px 1px 2px black;">Описание: {{ product.description }}</p>
                    <p style="text-shadow: 1px 1px 2px black;">Цена: {{ product.price }} руб.</p>
                    <p style="text-shadow: 1px 1px 2px black;">Скидка: {% firstof product.discount '0' %} руб.</p>
                    <p style="text-shadow: 1px 1px 2px black;">Просмотры: {{ product.views_count }} раз(-a)</p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>Тут пока ничего нет :(</h3>
    {% endif %}
    {% if perms.shopapp.add_product %}
        <div>
            <a style="padding-left: 120px; text-decoration: underline; color: white; font-size: 20px;" href="{% url 'shopapp:product-create'%}">Добавить товар</a>
        </div>
    {% endif %}
{% endblock %}

shopapp/templates/shopapp/profile_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Редактирование профиля
{% endblock %}

{% block body %}
  <h1>Редактирование профиля</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Сохранить</button>
    </form>
    <button type="submit"><a class="back" href="{% url 'shopapp:about-me'%}"> назад</a></button>
  </div>
{% endblock %}

shopapp/templates/shopapp/register.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <h1 style="padding-left: 120px; color: white; font-size: 40px;">Регистрация</h1>
  <form method="POST" style="padding-left: 120px; padding-bottom: 50px; padding-top: 50px;">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться">
  </form>
{% endblock %}

shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    TEAhouse
{% endblock %}

{% block body %}
    <h1 style="text-align: center; color: white; font-size: 40px;">НОВИНКИ</h1>
    <div  style="display: flex; justify-content: center; padding-bottom: 50px;">
        {% for product in products %}
            <div style="color: white; text-align: center;">
                <h1><a style="text-decoration: underline; color: white;" href="{% url 'shopapp:product_details' pk=product.pk %}">{{ product.name }}</a></h1>
                <div>
                    {% if product.preview %}
                        <img style="width: 400px; height: 250px;" src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                    {% endif %}
                </div>
                <p style="text-shadow: 1px 1px 2px black;">Описание: {{ product.description }}</p>
                <p style="text-shadow: 1px 1px 2px black;">Цена: {{ product.price }} руб.</p>
                <p style="text-shadow: 1px 1px 2px black;">Скидка: {% firstof product.discount '0' %} руб.</p>
                <p style="text-shadow: 1px 1px 2px black;">Просмотры: {{ product.views_count }} раз(-a)</p>
            </div>
        {% endfor %}
    </div>
    <p style="text-align: center; color: white; font-size: 30px;">{% if num_visits == 0 %} Вы впервые на нашем сайте!{% else %} Вы посетили наш сайт: {{ num_visits }} раз(-а){% endif %}</p>


{% endblock %}